### ISSUE TITLE
RankedChoiceVotingResult -modelin vote_count kokonaisluvusta desimaaliluvuksi

### ISSUE THREAD

**Issue by kalh** [Prodeko/vaalikoppi#20]
Siirtoäänivaalitavassa joissakin tapauksissa ääniä uudelleenjakaessa pudonneilta ehdokkailta voidaan jakaa vain esim. puolikkaita ääniä, jolloin vote_count tulisi olla myös float-tyyppinen. Templaten puolella kuitenkin kannattanee miettiä formatointia, esim. näyttää tulokset ilman desimaalipistettä jos kaikki tulokset on kokonaislukuja.

**Comment by skivinen** [comment]
Korjattu tuotannossa. Formatoinnit täytyy viel kattoo läpi

**Comment by skivinen** [comment]
Increase decimals to 3
