### ISSUE TITLE
TypeError: StopIteration interacts badly with generators and cannot be raised into a Future

### ISSUE THREAD

**Issue by rriski** [Prodeko/vaalikoppi#24]
Vaalikoppi kaatuu välillä seuraavaan erroriin:

![image](https://user-images.githubusercontent.com/25483483/99976555-429ad400-2dac-11eb-801b-18d6b5a6438f.png)

Liittyy todennäköisesti näihin riveihin: https://github.com/Prodeko/election/blob/5d30df423a750467d3c70eeaad5726d857381362/vaalikoppi/views/helpers.py#L41,  https://github.com/Prodeko/election/blob/5d30df423a750467d3c70eeaad5726d857381362/vaalikoppi/views/helpers.py#L56

Ratkaisu: ei käytetä next, vaan kirjoitetaan toisella tavalla.

**Comment by skivinen** [comment]
Tämä on tapahtunut tuotannossa todistetusti siis äänestyksen _sulkemisen_ jälkeen

**Comment by skivinen** [comment]
Ruma fiksi laitettu tuotannossa. Siistittävä.

**Comment by skivinen** [comment]
Apparently fixed
